export default {
    //通用
    common: {
        //常规通用
        closeRightTabs: '关闭右侧标签',
        closeAllTabs: '关闭全部标签',
        closeOtherTabs: '关闭其它标签',
        language: '语言',
        empty: '没有相关数据',
        totalText: '共',
        recordUnit: '条',
        condition: '条件',
        default: '默认',
        setDefault: '设为默认',
        file: '文件',
        username: '用户名',
        password: '密码',
        login: '登录',
        keyword: '关键词',
        selectPlaceholder: '请选择',
        inputPlaceholder: '请输入',
        plus: '添加',
        add: '新增',
        batchPlus: '批量添加',
        update: '修改',
        edit: '编辑',
        delete: '删除',
        save: '保存',
        cancel: '取消',
        confirm: '确定',
        search: '搜索',
        reset: '重置',
        detail: '详情',
        view: '查看',
        import: '导入',
        export: '导出',
        set: '设置',
        click: '点击',
        play: '播放',
        submit: '提交',
        upload: '上传',
        type: '类型',
        operator: '操作符',
        value: '值',
        operation: '操作',
        num: '序号',
        createTime: '创建时间',
        endTime: '结束时间',
        time: '时间',
        description: '描述',
        status: '状态',
        yes: '是',
        no: '否',
        open: '开启',
        close: '关闭',
        enable: '启用',
        disable: '禁用',
        pause: '暂停',
        stop: '停止',
        sort: '排序',
        image: '图片',
        video: '视频',
        baseInfo: '基本信息',
        confirmToLogout: '确定要退出登录吗？',
        confirmToDelete: '确定要删除吗？',
        confirmToClose: '确定要关闭吗？',
        confirmToClearALL: '确定要清除全部吗？',
        confirmToComplete: '确定已完成？',
        confirmToUpdate: '确定修改？',
        saveSuccess: '保存成功',
        deleteSuccess: '删除成功',
        downloadSuccess: '下载成功',
        importSuccess: '导入成功',
        uploadSuccess: '上传成功',
        operationSuccess: '操作成功',
        syncSuccess: '同步成功',
        actionSuccess: '操作成功',
        updateSuccess: '修改成功',
        selectFile: '选择文件',
        lastOneWarn: '已经是最后一个了，不能再关闭',
        lastOneDeleteWarn: '已经是最后一个，不能再删除了',
        errorNotFound: '抱歉，你访问的页面不存在',
        errorNoPermission: '抱歉，你无权访问该页面',
        errorSystem: '抱歉，服务器出错了',
        dataActioning: '数据操作中',
        dataLoading: '数据传输中',
        dataSaving: '数据保存中',
        dataDeleting: '数据删除中',
        fileDownloading: '文件下载中',
        dataImporting: '数据导入中',
        dataUploading: '文件上传中',
        dataSyncing: '数据同步中',
        reBootLoading: '重启中',
        deleteNoDataWarn: '至少选择一条要删除的数据',
        selectFileWarn: '选择要上传的文件',
        fileTypeError: '文件格式错误',
        descriptionLengthWarn: '描述不能超过100个字符',
        fileSizeWarn20MB: '文件不能超过20MB',
        networkError: '请检查网络是否断开',
        timeout: '请求超时请重新再试',
        action: '动作',
        icon: '图标',
        url: '路由地址',
        user: '用户',
        remark: '备注',
        all: '全部',
        canSelect: '可选择',
        selected: '已选择',
        group: '组',
        list: '列表',
        field: '字段',
        sync: '同步',
        downloadTpl: '下载模板',
        routine: '常规',
        complete: '完成',
        isDefault: '是否默认',
        isEnable: '是否启用',
        isDisabled: '是否禁用',
        isDisplay: '是否展示',
        isFrozen: '是否冻结',
        attribute: '属性',
        attributeValue: '属性值',
        clearAll: '清除全部',
        plusAll: '全部添加',
        position: '位置',
        date: '日期',
        dateRange: '起止日期',
        quantity: '数量',
        multiple: '多选',
        advancedSearch: '高级查询',
        query: '查询',
        theme: '主题',
        themeLight: '浅色',
        themeDark: '深色',
        more: '更多',
        normal: '正常',
        abnormal: '异常',
        //业务通用
        inaHome: '衣拿首页',
        sysName: 'INA智能生产管理系统',
        welcomeToUse: '欢迎使用',
        hangerQuery: '衣架查询',
        category: '分类',
        station: '站位',
        blsName: '站位名称',
        blsCode: '站位编号',
        orderNo: '订单编号',
        parent: '父级',
        name: '名称',
        code: '编码',
        tag: '标签',
        lineMap: '路线图',
        conditionFieldEmptyWarn: '请选择条件字段',
        conditionOperatorEmptyWarn: '请选择条件操作符',
        conditionValueEmptyWarn: '请选择条件值',
        fileContextPs: 'PS：右击下方列表可进行[设为默认][删除]操作。',
        attributeValueEmptyWarn: '请选择属性值',
        tagCode: '标签号',
        procedure: '工序',
        procedureName: '工序名称',
        procedureCode: '工序编号',
        employeeName: '员工姓名',
        employeeCode: '员工编号',
        departmentName: '部门名称',
        clothName: '样衣名称',
        clothCode: '样衣编号',
        clothCategory: '样衣分类',
        procedureFlow: '工序流',
        storeName: '仓位名称',
        storeCode: '仓位编号',
        carrier: '载具',
        carrierId: '载具编号',
        lineName: '仓位线名称',
        stockOutCode: '出库单号',
        stockOutExpectTime: '预计出库时间',
        lineCode: '线号',
        task: '任务',
        taskDetail: '任务详情',
        outDetail: '出库详情',
        currentPosition: '当前位置',
        targetPosition: '目标位置',
        updateTime: '最后更新时间',
        outControl: '出库控制',
        noLimitPlaceholder: '不输入或0代表不限制数量',
        noLimit: '不限',
        inTimeControl: '实时监控',
        customCode: '自定义编号',
        yesterdayDataStatistics: '昨日数值统计',
        yesterdayInCount: '昨日入库数量',
        yesterdayOutCount: '昨日出库数量',
        todayDataStatistics: '今日数值统计',
        todayInCount: '今日入库数量',
        todayOutCount: '今日出库数量',
        workerProductionStatistics: '员工生产统计',
        stationProductionStatistics: '站位生产统计',
        today: '今日',
        at: '在',
        packed: '完成了',
        pcs: '个',
        skuStatistics: '今日Sku统计',
        stationIn: '进仓',
        stationOut: '出仓',
        calresult: '计算结果',
        repair: '返修',
        InfeedName: '进轨名称',
        InfeedCode: '进轨编号',
        return: '返回',
        registerMsg: '请先注册',
        register: '注册',
        reboot: '重启',
        registered: '已注册信息',
        downloadLink: '下载文件',
        operateCircuit: '操作流程',
        extendAttr: '扩展属性',
    },
    //路由
    url: {
        home: '主页',
        exception: '错误异常',
        redirect: '加载中',
        account: '我的',
        account_info: '账号信息',
        account_notification: '消息通知',
        account_password: '修改密码',
        hangerquery: '${common.hangerQuery}',

        /*   system: "系统综合管理",
        system_menu: "系统菜单",
        system_padmenu: "平板菜单",
        system_lang: "语言管理",
        system_lang_version: "版本管理",
        system_lang_translate: "翻译管理",
        system_role: "角色管理",
        system_parameter: "系统参数",
        system_log: "日志管理",
        system_log_operation: "操作日志",
        system_log_run: "运行日志",
        system_classify: "数据字典",
        system_software: "软件更新",
        system_file: "文件管理",
        hr: "人事基础管理",
        hr_org: "组织机构",
        hr_employee: "员工信息",
        pm: "生产综合管理",
        pm_tags: "标签管理",
        dm: "基础数据管理",
        dm_programme: "分流方案",
        dm_attribute: "属性管理",
        dm_attribute_value: "属性值管理",
        dm_procedure: "工序管理",
        dm_flow: "工序流管理",
        dm_timer: "定时器管理",
        dm_order: "订单管理",
        dm_farelation: "工序流属性",
        dm_clothcate: "${common.clothCategory}",
        dm_cloth: "样衣管理",
        dm_group: "组别管理",
        dm_attributebindquantity:"衣架绑定数管理",
        pdm: "生产数据管理",
        pdm_vehicletrackrecord: "载具跟踪记录",
        pdm_productiondata: "员工生产数据",
        pdm_appointmentrecord: "预约记录",
        pdm_borrowrecord: "借还记录",
        pdm_borrowwarn: "借还预警",
        pdm_hanger: "衣架管理",
        pdm_productiondataerror: "上报失败数据",
        pdm_repairrecord: "返修记录",
        layout: "布局通信设置",
        layout_factory: "工厂管理",
        layout_shuntschemeset: "仓位分流方案",
        layout_exhibition: "布局结构",
        layout_padrelation: "平板绑定管理",
        warehouse: "仓库管理",
        warehouse_stockin: "入库信息",
        warehouse_stockout: "出库信息",
        warehouse_statisticsin: "入库统计",
        warehouse_statisticsout: "出库统计",
        warehouse_capacity: "${capacity.title}",
        warehouse_autooutcontrol: "自动出库控制",
        warehouse_autooutscheme: "自动出库方案",
        warehouse_stock: "库存管理",
        warehouse_outcontrol: "${common.outControl}",
        warehouse_outtask: "出库任务",
        warehouse_inoutsummaryreport: "出入库汇总统计", */
    },
    home: {
        returnMsg: '_预计在_时间前归还_样衣',
        employeewarning: '员工借还预警',
        sampleStatistics: '样衣统计',
    },
    //我的
    account: {
        info: '账号信息',
        password: '修改密码',
        notification: '消息通知',
        logout: '退出登录',
        loginIp: '最后登录IP',
        loginTime: '最后登录时间',
        currentPassword: '当前密码',
        newPassword: '新密码',
        confirmPassword: '确认密码',
        confirmPasswordError: '确认密码错误',
    },
    //员工
    employee: {
        name: '姓名',
        code: '工号',
        sex: '性别',
        role: '${url.system_role}',
        organization: '组织机构',
        phone: '手机号码',
        avatar: '照片',
        attendanceId: '考勤卡号',
        idNumber: '身份证',
        man: '男',
        woman: '女',
        birthday: '生日',
        education: '文化程度',
        address: '联系地址',
        workType: '工种',
        cardNumber: '工资卡号',
        employmentDate: '入职日期',
        resignationDate: '离职日期',
        age: '年龄',
        nation: '民族',
        height: '身高',
        weight: '体重',
        marriage: '婚姻状况',
        defaultPassword: '默认密码',
        addressLengthLimit: '不能超过100个字符',
        negativeNumberLimit: '不能为负数',
    },
    //系统菜单
    sysMenu: {
        commonNode: '常用节点',
        nodeExistWarn: '该节点已存在，不要重复添加',
        emptyUrlWarn: '未找到该路由地址配置信息',
        node: '节点',
    },
    //语言
    language: {
        name: '语言名称',
        flag: '语言标识',
        ps: '鼠标移动至下方表格单元格内并单击，可设置修改译文。',
        importFile: '导入文件',
        importPs1: '选择相应的语言',
        importPs2: '点击“下载模板”（非必要）',
        importPs3: '填好模板里的翻译内容',
        importPs4: '点击“导入文件”',
        importPs5: '选择要导入的文件',
    },
    //角色
    role: {
        permission: '权限',
    },
    //操作日志
    sysOperationLog: {
        url: '访问地址',
        useTime: '总耗时',
        requestData: '请求参数',
        responseData: '响应参数',
    },
    //软件更新
    software: {
        category: '软件分类',
        versionCode: '版本号',
        content: '更新内容',
        contentLengthWarn: '不能超过50个字符',
    },
    //标签信息
    tags: {
        tagCode: '${common.tagCode}',
        batchCode: '批次号',
        bindingQuantity: '绑定数量',
        customCode: '${common.customCode}',
        salesOrderId: '销售订单号',
        process: '进度信息',
        poiCode: '${common.procedureCode}',
        carrierId: '衣架号',
        finishTime: '完成时间',
        statusDisabled: '停用',
        statusNew: '新建',
        statusProduction: '生产中',
        statusStock: '库存',
        statusOutStock: '已出库',
        statusRepair: '返修',
        statusComplete: '${common.complete}',
    },
    //衣架查询
    hangerQuery: {
        currentPosition: '${common.currentPosition}',
        targetPosition: '${common.targetPosition}',
        hangerCode: '衣架编号',
        stockStatus: '库存状态',
        clothName: '样衣名称',
        clothCode: '样衣编号',
        clothStatusName: '样衣状态',
        clothWidth: '样衣厚度',
        blsUsing: '占用仓位',
        blsName: '仓位名称',
        blsCode: '仓位编号',
        clothAttr: '样衣属性',
    },
    //分流方案
    programme: {
        nameEmptyWarn: '请输入方案名称',
        stations: '已配置站位',
        stationAllocation: '站位分配',
    },
    //方案参数
    shuntschemerules: {
        optionmode: '选项方式',
        showmode: '展示模块',
        weight: '权重',
    },
    //工序
    procedure: {
        category: '工序分类',
        isRecordProductionData: '是否记产量',
        isFindForSameSKU: '相同SKU优先进入同站位',
    },
    //工序流
    flow: {
        editPs: '从左侧拖曳工序至右侧工序流中，并进行排序',
        editLeftEmpty: '已无可选流程',
        editRightEmpty: '暂无选择流程',
        empty: '未设置工序流',
        same_sku: '是否相同SKU优先进入相同站位',
        sku_compse: 'SKU组合',
        max_sku: '同端最多存几个SKU',
        sku_setting: '路线图SKU设置',
    },
    //订单
    order: {
        statusNew: '${tags.statusNew}',
        statusProduction: '${tags.statusProduction}',
        statusComplete: '${tags.statusComplete}',
    },
    //样衣分类
    clothCategory: {
        displayAttrMaxNumLimit: '最多展示4个属性',
    },
    //样衣
    cloth: {
        thickness: '厚度',
        statusNormal: '正常',
        statusBorrowing: '借出',
        statusOut: '出仓',
        bindingNumber: '绑定的衣架号',
    },
    //载具跟踪记录
    vehicleTrackRecord: {
        eventName: '事件名称',
        eventType: '事件类型',
        labelCustomNo: '标签自定义编号',
    },
    //预约记录
    appointmentRecord: {
        code: '预约单编号',
        time: '预约时间',
        timeStart: '预约开始时间',
        timeEnd: '预约结束时间',
        statusException: '异常',
        statusNew: '${tags.statusNew}',
        statusNormal: '${cloth.statusNormal}',
        statusBorrowing: '${cloth.statusBorrowing}',
        statusOut: '${cloth.statusOut}',
    },
    //借还记录/预警
    clothBorrow: {
        borrowTime: '出借时间',
        returnUserName: '归还员工',
        returnTime: '归还时间',
        expectReturnTime: '预计归还时间',
        statusBorrowing: '${cloth.statusBorrowing}',
        statusBound: '已绑定，待入库',
        statusReturn: '已归还',
    },
    //入库信息
    stockIn: {
        code: '入库单号',
        enterMode: '入库方式',
        enterTime: '入库时间',
    },
    //出库信息
    stockOut: {
        portName: '出货口名称',
        portCode: '出货口编号',
    },
    //入库统计
    statisticsIn: {
        carrierUpdateTime: '载具最后更新时间',
        carrierEnterTime: '载具入库时间',
        enterTime: '${stockIn.enterTime}',
        labelCustomNo: '标签自定义编号',
    },
    //出库统计
    statisticsOut: {
        carrierUpdateTime: '${statisticsIn.carrierUpdateTime}',
        carrierOutTime: '载具出库时间',
        outTime: '出库时间',
        labelCustomNo: '标签自定义编号',
    },
    //出入库汇总统计
    Inoutsummaryreport: {
        onnum: '库存数量',
        innum: '入仓数量',
        outnum: '出仓数量',
        currentstatistics: '当前统计',
        daystatistics: '日统计',
        monthstatistics: '月统计',
    },
    //库区容量
    capacity: {
        title: '库区容量',
        look: '库区容量监控',
        currentLine: '当前线',
        total: '总容量',
        used: '已占用容量',
        surplus: '剩余容量',
        usedRate: '占用率',
    },
    //出库控制
    outControl: {
        outOrder: '出库单',
        orderCode: '出仓任务订单号',
        pickingOrderCode: '领料单号',
        whInCode: '调入仓库',
        whOutCode: '调出仓库',
        outDetail: '出库详情',
    },
    //出库任务
    outtask: {
        Inprogress: '出库中',
        pause: '${common.pause}',
        close: '${common.close}',
        complete: '${common.complete}',
    },
    //自动出库方案
    autoOutScheme: {
        targetStation: '目的站位',
        currentLine: '${capacity.currentLine}',
    },
    //仓库
    stock: {
        emptyData: '没有可出库的数据',
        maxDataNum: '当前最多可出库数量',
        stockInTime: '入库时间',
        handleOut: '手动出库',
        outTitle: '出库单',
        blsInfo: '站位信息',
        autoSelectPort: '自动选择出货口',
        batchSelectPort: '批量选择出货口',
        outPort: '出货口',
        frozenWarn: '已冻结记录不允许再次出库',
        inStartTime: '入库开始时间',
        inEndTime: '入库结束时间',
        caltime: '计算隧道机时间',
    },
    //布局结构
    exhibition: {
        coverImportPs: '导入成功后仓位对应的分流方案将会被替换',
        belongToFactory: '所属工厂',
        layoutType: '布局结构类型',
        layoutName: '布局结构名称',
        layoutCode: '布局结构编号',
        layoutStatus: '布局结构状态',
        rule: '规则',
        softfullflag: '是否软满',
        hardwarefullflag: '是否硬满',
    },
    //平板绑定
    padrelation: {
        pad_mac: 'MAC',
        Bindblscode: '绑定站位编号',
        Bindblsname: '绑定站位名称',
        oldsourcestationid: '吊挂站位号',
    },
    //衣架
    hanger: {
        currentPositionStationCode: '当前站位编号',
        currentPositionStationName: '当前站位名称',
        currentPositionCode: '当前位置编号',
        targetPositionStationCode: '目标站位编号',
        targetPositionCode: '目标位置编号',
        curOrDesStationCode: '当前位置或目标位置编号',
        confirmToClear: '确定要清理所选择的衣架数据？',
        clearNoDataWarn: '请选择要清理的衣架数据',
        clear: '衣架数据清理',
        status: '载具状态',
        changeStatus: '更改载具状态',
        selectWarn: '请选择衣架',
        confirmChangeStatus:'确定要更改衣架的载具状态吗？'
    },
    //运行日志
    runLog: {
        page: '页码',
        pageSize: '分页大小',
        rootDir: '根目录',
        batchPull: '批量拉取',
        pull: '拉取',
    },
    //运行日志
    file: {
        name: '原始文件名',
        path: '文件路径',
        size: '文件大小',
    },
    //工序流属性
    farelation: {
        descriptionLengthWarn: '描述不能超过40个字符',
    },
    //上报失败数据
    productionDataError: {
        method: '方法',
        requestData: '请求数据',
        url: '请求地址',
        repeatCount: '重新发送次数',
        statusDoing: '处理中',
        confirmToRePost: '确定要重新上报吗？',
        hasRePosted: '已重新上报',
        rePost: '重新上报',
        responseResult: '响应结果',
    },
    attributebindquantity: {
        pca_englishname: '自定义属性',
        pcad_value: '值',
        quantity: '数量',
        create_time: '创建时间',
    },
    login: {
        registerStepOne: '一、将下载的文件发送服务商注册授权文件。',
        registerStepTwo: '二、获得文件后，点击右侧链接进行信息注册。',
        registerStepThree: '三、',
        registerLink: '（注册链接）',
        rebootSystem: '重启系统',
        registerSuccessMsg: '已注册成功！欢迎使用！',
        authFile: '授权文件',
        iptAuthFile: '请输入授权文件',
        systemName: '系统名称',
        iptSystemName: '请输入系统名称',
        expireTime: '到期时间',
        iptExpireTime: '请输入到期时间',
        copy: '版权',
        iptCopy: '请输入版权',
        expireTimeMsg: '距离到期时间还有_天，请及时',
    },
    weightmanagement: {
        feasibleLine: '可行线',
        weight: '重量',
        saveMsg: '可行线',
    },
    inventoryRecord:{
        lineName:'线号名称',
        lineCode:'线号编号',
        singleNumber:'单号'
    },
};
